service: finalChallenge

custom:
  webpack:
      webpackConfig: ./webpack.config.js
      includeModules: true
  dynamodb:
    stages:
      - dev
      - local
    start:
      port: 8000
      inMemory: true
      migrate: true
  serverless-offline:
    httpPort: 4000


provider: 
  name: aws
  runtime: nodejs14.x
  region: sa-east-1
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    lambdaHashingVersion: 20201221

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-dynamodb-local

functions:
  create:
    handler: src/functions/addTodo.handle
    events:
      - http:
          path: todos/{userid}
          method: post
          cors: true
        
  get:
    handler: src/functions/listTodo.handle
    events:
      - http:
          path: todos/{userid}
          method: get
          cors: true
        

resources:
  Resources:
    TodosDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: userid
            AttributeType: S
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: userid
            KeyType: HASH
          -
            AttributeName: id
            KeyType: RANGE

        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TableName: todos_table